// Quick test: does Ollama respond, and does the story engine produce output?
// Run with: node test-story.mjs

import { buildStoryPrompt } from './src/prompts/story.prompt.js';

const OLLAMA_URL = process.env.OLLAMA_BASE_URL || 'http://localhost:11434';
const MODEL      = process.env.OLLAMA_MODEL || 'qwen2.5:7b';
const TIMEOUT_MS = 180000; // 3 min — CPU-only inference is slow (AMD driver blocks GPU)

async function testOllamaAlive() {
  console.log(`\n[1] Checking Ollama server at ${OLLAMA_URL}/api/tags ...`);
  try {
    const ctrl = new AbortController();
    setTimeout(() => ctrl.abort(), 5000);
    const res = await fetch(`${OLLAMA_URL}/api/tags`, { signal: ctrl.signal });
    const data = await res.json();
    const models = (data.models || []).map(m => m.name);
    console.log(`    ✅ Ollama is RUNNING. Available models: ${models.join(', ') || '(none pulled)'}`);
    const hasModel = models.some(m => m.startsWith(MODEL.split(':')[0]));
    if (!hasModel) {
      console.warn(`    ⚠️  Model "${MODEL}" not found. Run: ollama pull ${MODEL}`);
    } else {
      console.log(`    ✅ Model "${MODEL}" is available.`);
    }
    return true;
  } catch (e) {
    console.error(`    ❌ Ollama is NOT running or unreachable: ${e.message}`);
    return false;
  }
}

async function testStoryGeneration() {
  console.log(`\n[2] Testing story generation with model "${MODEL}" ...`);
  const prompt = buildStoryPrompt({ theme: 'classic_mansion', seed: 'TEST123', playerCount: 3 });

  try {
    const ctrl = new AbortController();
    setTimeout(() => ctrl.abort(), TIMEOUT_MS);

    const res = await fetch(`${OLLAMA_URL}/api/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ model: MODEL, prompt, stream: false, temperature: 0.7, num_predict: 2048 }),
      signal: ctrl.signal,
    });

    const raw = await res.text();

    let ollamaJson;
    try { ollamaJson = JSON.parse(raw); } catch {
      console.error(`    ❌ Ollama returned non-JSON: ${raw.slice(0, 300)}`);
      return;
    }

    const responseText = ollamaJson.response || ollamaJson.result || '';
    if (!responseText) {
      console.error('    ❌ Ollama returned an empty response field.');
      console.log('    Raw Ollama response:', JSON.stringify(ollamaJson, null, 2));
      return;
    }

    console.log(`    ✅ Ollama responded (${responseText.length} chars). Parsing story JSON...`);

    // Strip chain-of-thought <think>...</think> tags
    const cleaned = responseText.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();

    const jsonMatch = cleaned.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      console.error('    ❌ No JSON object found in AI response.');
      console.log('    First 500 chars of response:\n', responseText.slice(0, 500));
      return;
    }

    let storyData;
    try {
      storyData = JSON.parse(jsonMatch[0]);
    } catch (e) {
      console.error(`    ❌ JSON parse failed: ${e.message}`);
      console.log('    JSON attempt:\n', jsonMatch[0].slice(0, 500));
      return;
    }

    console.log('\n    ✅ Story successfully generated by AI!\n');
    console.log('    ── Story Summary ──────────────────────────────');
    console.log(`    Theme     : ${storyData.theme}`);
    console.log(`    World     : ${storyData.world}`);
    console.log(`    Crime     : ${storyData.crime}`);
    console.log(`    Victim    : ${storyData.victim}`);
    console.log(`    Murderer  : ${storyData.murderer}`);
    console.log(`    Weapon    : ${storyData.murderWeapon}`);
    console.log(`    Location  : ${storyData.location}`);
    console.log(`    Time      : ${storyData.timeOfDeath}`);
    console.log(`    Motive    : ${storyData.motiveSummary}`);
    const suspects = storyData.suspects || [];
    console.log(`    Suspects  : ${suspects.length} generated`);
    suspects.forEach((s, i) => {
      console.log(`      [${i+1}] ${s.name} (${s.occupation}) — murderer: ${s.isMurderer}`);
    });
    const rooms = storyData.mapConfig?.rooms || [];
    console.log(`    Map rooms : ${rooms.map(r => r.name).join(', ') || '(none)'}`);
    console.log('    ───────────────────────────────────────────────\n');

  } catch (e) {
    if (e.name === 'AbortError') {
      console.error(`    ❌ Request timed out after ${TIMEOUT_MS/1000}s — model may be loading or too slow.`);
    } else {
      console.error(`    ❌ Generation failed: ${e.message}`);
    }
  }
}

(async () => {
  const alive = await testOllamaAlive();
  if (alive) await testStoryGeneration();
  else console.log('\n    ⛔ Skipping story generation test — Ollama is not running.\n');
})();
